version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    volumes:
      - ${HOST_USER_HOME}:/host_home:ro
    environment:
      - BASE_DIR=/host_home
      - RABBITMQ_URL=rabbitmq://rabbitmq:5672  # Подключение к RabbitMQ
    depends_on:
      - rabbitmq
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - dev

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"  # UI RabbitMQ Management
      - "5672:5672"    # основной порт для RabbitMQ
    networks:
      - dev
