networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8082:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
      - file_api
    networks:
      - dev

  backend:
    build:
      context: ./backend
    volumes:
      - ${HOST_USER_HOME}:/home
    environment:
      - BASE_DIR=/home
    env_file:
      - ./file_api/.env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
      - file_api
      - rabbitmq
    networks:
      - dev

  file_api:
    build:
      context: ./file_api
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - backend
      - rabbitmq
    volumes:
    - ${HOST_USER_HOME}:/home
    ports:
    - "8083:8080"
    networks:
      - dev
    

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - dev
