version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    volumes:
      - ${HOST_USER_HOME}:/host_home:ro
    environment:
      - BASE_DIR=/host_home
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - dev